import type { FastifyReply, FastifyRequest } from 'fastify';
import { toPaginationParams } from '../../common/utils/pagination.js';
import { mutationContext, requireTenant, validatedBody, validatedParams, validatedQuery } from '../../common/utils/request-context.js';
import { ok, paginated } from '../../common/utils/response.js';
import type { CreateDocumentTemplateBody, CreateDocumentTemplateVersionBody, DocumentTemplateIdParam, DocumentTemplateListQuery, FinalizeGeneratedDocumentBody, GeneratedDocumentIdParam, GeneratedDocumentListQuery, GeneratedDocumentPatientIdParam, GeneratedDocumentReasonBody, PreviewGeneratedDocumentBody, UpdateDocumentTemplateBody } from './generated-document.schema.js';
import { documentTemplateService, generatedDocumentService } from './generated-document.service.js';

export async function listDocumentTemplatesHandler(request: FastifyRequest, reply: FastifyReply) { const query = validatedQuery<DocumentTemplateListQuery>(request); const pagination = toPaginationParams(query); const result = await documentTemplateService.list(requireTenant(request).clinicId, { ...(query.status ? { status: query.status } : {}), ...(query.category ? { category: query.category } : {}), ...(query.code ? { code: query.code } : {}) }, pagination); return reply.send(paginated(result, pagination)); }
export async function createDocumentTemplateHandler(request: FastifyRequest, reply: FastifyReply) { const value = await documentTemplateService.create(requireTenant(request).clinicId, validatedBody<CreateDocumentTemplateBody>(request), mutationContext(request)); return reply.status(201).send(ok(value)); }
export async function updateDocumentTemplateHandler(request: FastifyRequest, reply: FastifyReply) { const value = await documentTemplateService.updateDraft(requireTenant(request).clinicId, validatedParams<DocumentTemplateIdParam>(request).templateId, validatedBody<UpdateDocumentTemplateBody>(request), mutationContext(request)); return reply.send(ok(value)); }
export async function createDocumentTemplateVersionHandler(request: FastifyRequest, reply: FastifyReply) { const value = await documentTemplateService.createVersion(requireTenant(request).clinicId, validatedParams<DocumentTemplateIdParam>(request).templateId, validatedBody<CreateDocumentTemplateVersionBody>(request), mutationContext(request)); return reply.status(201).send(ok(value)); }
export async function activateDocumentTemplateHandler(request: FastifyRequest, reply: FastifyReply) { const value = await documentTemplateService.activate(requireTenant(request).clinicId, validatedParams<DocumentTemplateIdParam>(request).templateId, mutationContext(request)); return reply.send(ok(value)); }
export async function archiveDocumentTemplateHandler(request: FastifyRequest, reply: FastifyReply) { const value = await documentTemplateService.archive(requireTenant(request).clinicId, validatedParams<DocumentTemplateIdParam>(request).templateId, mutationContext(request)); return reply.send(ok(value)); }
export async function listPatientGeneratedDocumentsHandler(request: FastifyRequest, reply: FastifyReply) { const pagination = toPaginationParams(validatedQuery<GeneratedDocumentListQuery>(request)); const result = await generatedDocumentService.listForPatient(requireTenant(request).clinicId, validatedParams<GeneratedDocumentPatientIdParam>(request).patientId, pagination); return reply.send(paginated(result, pagination)); }
export async function previewGeneratedDocumentHandler(request: FastifyRequest, reply: FastifyReply) { const tenant = requireTenant(request); const context = mutationContext(request); const value = await generatedDocumentService.preview(tenant.clinicId, validatedParams<GeneratedDocumentPatientIdParam>(request).patientId, validatedBody<PreviewGeneratedDocumentBody>(request), tenant, context.actorUserId); return reply.send(ok(value)); }
export async function finalizeGeneratedDocumentHandler(request: FastifyRequest, reply: FastifyReply) { const tenant = requireTenant(request); const value = await generatedDocumentService.finalize(tenant.clinicId, validatedParams<GeneratedDocumentPatientIdParam>(request).patientId, validatedBody<FinalizeGeneratedDocumentBody>(request), tenant, mutationContext(request)); return reply.status(201).send(ok(value)); }
export async function getGeneratedDocumentHandler(request: FastifyRequest, reply: FastifyReply) { const value = await generatedDocumentService.getById(requireTenant(request).clinicId, validatedParams<GeneratedDocumentIdParam>(request).documentId); return reply.send(ok(value)); }
export async function downloadGeneratedDocumentPdfHandler(request: FastifyRequest, reply: FastifyReply) { const value = await generatedDocumentService.downloadPdf(requireTenant(request).clinicId, validatedParams<GeneratedDocumentIdParam>(request).documentId); return reply.type('application/pdf').header('Cache-Control', 'private, no-store').header('Content-Disposition', `inline; filename="${value.fileName}"`).send(value.content); }
export async function voidGeneratedDocumentHandler(request: FastifyRequest, reply: FastifyReply) { const value = await generatedDocumentService.void(requireTenant(request).clinicId, validatedParams<GeneratedDocumentIdParam>(request).documentId, validatedBody<GeneratedDocumentReasonBody>(request).reason, mutationContext(request)); return reply.send(ok(value)); }
