/**
 * Stable, machine-readable error codes returned as `error.code`.
 *
 * Clients branch on these strings, so they are part of the public API contract:
 * rename one and you break a client. Messages may change freely; codes may not.
 */
export const ERROR_CODES = {
  // --- Generic ---------------------------------------------------------
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  BUSINESS_RULE_VIOLATION: 'BUSINESS_RULE_VIOLATION',
  RATE_LIMITED: 'RATE_LIMITED',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',

  // --- Authentication --------------------------------------------------
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  MISSING_ACCESS_TOKEN: 'MISSING_ACCESS_TOKEN',
  INVALID_ACCESS_TOKEN: 'INVALID_ACCESS_TOKEN',
  ACCESS_TOKEN_EXPIRED: 'ACCESS_TOKEN_EXPIRED',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  REFRESH_TOKEN_REUSED: 'REFRESH_TOKEN_REUSED',
  SESSION_REVOKED: 'SESSION_REVOKED',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  AUTH_CODE_INVALID_OR_EXPIRED: 'AUTH_CODE_INVALID_OR_EXPIRED',
  AUTH_CODE_ATTEMPTS_EXCEEDED: 'AUTH_CODE_ATTEMPTS_EXCEEDED',
  SUPER_ADMIN_BOOTSTRAP_FORBIDDEN: 'SUPER_ADMIN_BOOTSTRAP_FORBIDDEN',

  // --- Tenancy / authorization ------------------------------------------
  CLINIC_CONTEXT_REQUIRED: 'CLINIC_CONTEXT_REQUIRED',
  CLINIC_CONTEXT_AMBIGUOUS: 'CLINIC_CONTEXT_AMBIGUOUS',
  CLINIC_ACCESS_DENIED: 'CLINIC_ACCESS_DENIED',
  MEMBERSHIP_INACTIVE: 'MEMBERSHIP_INACTIVE',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',

  // --- Domain -----------------------------------------------------------
  CLINIC_NOT_FOUND: 'CLINIC_NOT_FOUND',
  CLINIC_SLUG_TAKEN: 'CLINIC_SLUG_TAKEN',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  MEMBERSHIP_NOT_FOUND: 'MEMBERSHIP_NOT_FOUND',
  MEMBERSHIP_ALREADY_EXISTS: 'MEMBERSHIP_ALREADY_EXISTS',
  LAST_CLINIC_OWNER: 'LAST_CLINIC_OWNER',
  PATIENT_NOT_FOUND: 'PATIENT_NOT_FOUND',
  PATIENT_ALREADY_ARCHIVED: 'PATIENT_ALREADY_ARCHIVED',
  GUARDIAN_NOT_FOUND: 'GUARDIAN_NOT_FOUND',

  // --- Patient media -----------------------------------------------------
  MEDIA_NOT_FOUND: 'MEDIA_NOT_FOUND',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  INVALID_UPLOAD: 'INVALID_UPLOAD',
  MEDIA_UPLOAD_FAILED: 'MEDIA_UPLOAD_FAILED',
  INVALID_MEDIA_CATEGORY: 'INVALID_MEDIA_CATEGORY',
  MEDIA_ALREADY_ARCHIVED: 'MEDIA_ALREADY_ARCHIVED',
  FORBIDDEN_MEDIA_ACCESS: 'FORBIDDEN_MEDIA_ACCESS',

  // --- Scheduling --------------------------------------------------------
  APPOINTMENT_NOT_FOUND: 'APPOINTMENT_NOT_FOUND',
  APPOINTMENT_TYPE_NOT_FOUND: 'APPOINTMENT_TYPE_NOT_FOUND',
  APPOINTMENT_TYPE_NAME_TAKEN: 'APPOINTMENT_TYPE_NAME_TAKEN',
  APPOINTMENT_TYPE_INACTIVE: 'APPOINTMENT_TYPE_INACTIVE',
  /** The doctor already has an appointment overlapping this time range. */
  APPOINTMENT_TIME_CONFLICT: 'APPOINTMENT_TIME_CONFLICT',
  SLOT_CAPACITY_EXCEEDED: 'SLOT_CAPACITY_EXCEEDED',
  APPOINTMENT_OVERBOOKING_NOT_ALLOWED: 'APPOINTMENT_OVERBOOKING_NOT_ALLOWED',
  APPOINTMENT_INVALID_TIME_RANGE: 'APPOINTMENT_INVALID_TIME_RANGE',
  APPOINTMENT_OUTSIDE_WORKING_HOURS: 'APPOINTMENT_OUTSIDE_WORKING_HOURS',
  APPOINTMENT_INVALID_STATUS_TRANSITION: 'APPOINTMENT_INVALID_STATUS_TRANSITION',
  APPOINTMENT_ALREADY_CLOSED: 'APPOINTMENT_ALREADY_CLOSED',
  CLINIC_HAS_NO_DOCTOR: 'CLINIC_HAS_NO_DOCTOR',

  // --- Treatments --------------------------------------------------------
  TREATMENT_NOT_FOUND: 'TREATMENT_NOT_FOUND',
  /** A patient may only have one treatment actively running at a time. */
  TREATMENT_ALREADY_ACTIVE: 'TREATMENT_ALREADY_ACTIVE',
  TREATMENT_INVALID_STATUS_TRANSITION: 'TREATMENT_INVALID_STATUS_TRANSITION',
  TREATMENT_ALREADY_CLOSED: 'TREATMENT_ALREADY_CLOSED',
  TREATMENT_INVALID_DATE_RANGE: 'TREATMENT_INVALID_DATE_RANGE',
  TREATMENT_INVALID_TYPE: 'TREATMENT_INVALID_TYPE',
  TREATMENT_MILESTONE_NOT_FOUND: 'TREATMENT_MILESTONE_NOT_FOUND',
  TREATMENT_PATIENT_ARCHIVED: 'TREATMENT_PATIENT_ARCHIVED',

  // --- Cash records ------------------------------------------------------
  CASH_RECORD_NOT_FOUND: 'CASH_RECORD_NOT_FOUND',
  CASH_RECORD_ALREADY_CANCELLED: 'CASH_RECORD_ALREADY_CANCELLED',
  /** A recorded payment is never edited in place; cancel it and record a correction. */
  CASH_RECORD_CANNOT_BE_MODIFIED: 'CASH_RECORD_CANNOT_BE_MODIFIED',
  INVALID_AMOUNT: 'INVALID_AMOUNT',
  UNSUPPORTED_CURRENCY: 'UNSUPPORTED_CURRENCY',
  GUARDIAN_REQUIRED_FOR_PAYER_TYPE: 'GUARDIAN_REQUIRED_FOR_PAYER_TYPE',
  GUARDIAN_NOT_LINKED_TO_PATIENT: 'GUARDIAN_NOT_LINKED_TO_PATIENT',
  TREATMENT_PATIENT_MISMATCH: 'TREATMENT_PATIENT_MISMATCH',
  INVALID_RECEIVED_AT: 'INVALID_RECEIVED_AT',
  /**
   * Soft warning, not a failure: the clinic may still have physically received
   * the money. An authorized caller repeats the request with `allowOverpayment`.
   */
  PAYMENT_EXCEEDS_REMAINING_AMOUNT: 'PAYMENT_EXCEEDS_REMAINING_AMOUNT',
  OVERPAYMENT_APPROVAL_NOT_ALLOWED: 'OVERPAYMENT_APPROVAL_NOT_ALLOWED',
  /** Same idempotency key replayed with a different payload — a real client bug. */
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',

  // --- Receipts ----------------------------------------------------------
  RECEIPT_NOT_FOUND: 'RECEIPT_NOT_FOUND',
  RECEIPT_SEQUENCE_UNAVAILABLE: 'RECEIPT_SEQUENCE_UNAVAILABLE',

  // --- Infrastructure ----------------------------------------------------
  MEDIA_STORAGE_UNAVAILABLE: 'MEDIA_STORAGE_UNAVAILABLE',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
