/**
 * Stable, machine-readable error codes returned as `error.code`.
 *
 * Clients branch on these strings, so they are part of the public API contract:
 * rename one and you break a client. Messages may change freely; codes may not.
 */
export const ERROR_CODES = {
  // --- Generic ---------------------------------------------------------
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  BUSINESS_RULE_VIOLATION: 'BUSINESS_RULE_VIOLATION',
  RATE_LIMITED: 'RATE_LIMITED',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',

  // --- Authentication --------------------------------------------------
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  MISSING_ACCESS_TOKEN: 'MISSING_ACCESS_TOKEN',
  INVALID_ACCESS_TOKEN: 'INVALID_ACCESS_TOKEN',
  ACCESS_TOKEN_EXPIRED: 'ACCESS_TOKEN_EXPIRED',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  REFRESH_TOKEN_REUSED: 'REFRESH_TOKEN_REUSED',
  SESSION_REVOKED: 'SESSION_REVOKED',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  AUTH_CODE_INVALID_OR_EXPIRED: 'AUTH_CODE_INVALID_OR_EXPIRED',
  AUTH_CODE_ATTEMPTS_EXCEEDED: 'AUTH_CODE_ATTEMPTS_EXCEEDED',
  SUPER_ADMIN_BOOTSTRAP_FORBIDDEN: 'SUPER_ADMIN_BOOTSTRAP_FORBIDDEN',

  // --- Tenancy / authorization ------------------------------------------
  CLINIC_CONTEXT_REQUIRED: 'CLINIC_CONTEXT_REQUIRED',
  CLINIC_CONTEXT_AMBIGUOUS: 'CLINIC_CONTEXT_AMBIGUOUS',
  CLINIC_ACCESS_DENIED: 'CLINIC_ACCESS_DENIED',
  MEMBERSHIP_INACTIVE: 'MEMBERSHIP_INACTIVE',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',

  // --- Domain -----------------------------------------------------------
  CLINIC_NOT_FOUND: 'CLINIC_NOT_FOUND',
  CLINIC_SLUG_TAKEN: 'CLINIC_SLUG_TAKEN',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  MEMBERSHIP_NOT_FOUND: 'MEMBERSHIP_NOT_FOUND',
  MEMBERSHIP_ALREADY_EXISTS: 'MEMBERSHIP_ALREADY_EXISTS',
  LAST_CLINIC_OWNER: 'LAST_CLINIC_OWNER',
  PATIENT_NOT_FOUND: 'PATIENT_NOT_FOUND',
  PATIENT_ALREADY_ARCHIVED: 'PATIENT_ALREADY_ARCHIVED',

  // --- Infrastructure ----------------------------------------------------
  MEDIA_STORAGE_UNAVAILABLE: 'MEDIA_STORAGE_UNAVAILABLE',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
