import { readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import type PDFDocumentType from 'pdfkit';

const require = createRequire(import.meta.url);
const PDFDocument = require('pdfkit') as typeof PDFDocumentType;
const MANROPE_FONT = readFileSync(
  require.resolve('@fontsource-variable/manrope/files/manrope-latin-ext-wght-normal.woff2'),
);

export interface PdfClinicBranding {
  clinicName: string;
  doctorName: string | null;
  address: string | null;
  phone: string | null;
  email: string | null;
}

export function createOrthoFlowPdf(info: PDFKit.DocumentInfo): PDFKit.PDFDocument {
  const document = new PDFDocument({
    size: 'A4',
    margin: 54,
    bufferPages: true,
    compress: true,
    info: { ...info, Creator: 'OrthoFlow' },
  });
  document.registerFont('Manrope', MANROPE_FONT);
  return document.font('Manrope');
}

export function renderClinicHeader(
  document: PDFKit.PDFDocument,
  branding: PdfClinicBranding,
): void {
  document.fillColor('#173F38').fontSize(18).text(branding.clinicName);
  const identityLine = [branding.doctorName, branding.address, branding.phone, branding.email]
    .filter(Boolean)
    .join(' · ');
  if (identityLine) document.fillColor('#56635F').fontSize(9).text(identityLine);
  document.moveDown(0.8);
  document.strokeColor('#DCE2DE').moveTo(54, document.y).lineTo(541, document.y).stroke();
  document.moveDown(1.1);
}

export function renderDocumentFooters(
  document: PDFKit.PDFDocument,
  reference: string,
  generatedAtLabel: string,
): void {
  const range = document.bufferedPageRange();
  for (let pageIndex = range.start; pageIndex < range.start + range.count; pageIndex += 1) {
    document.switchToPage(pageIndex);
    document
      .strokeColor('#DCE2DE')
      .moveTo(54, 790)
      .lineTo(541, 790)
      .stroke();
    document
      .fillColor('#56635F')
      .fontSize(7.5)
      .text(`${reference} · ${generatedAtLabel} · Generated by OrthoFlow`, 54, 800, {
        width: 390,
        lineBreak: false,
      })
      .text(`Page ${pageIndex - range.start + 1} / ${range.count}`, 445, 800, {
        width: 96,
        align: 'right',
        lineBreak: false,
      });
  }
}

export async function finalizePdf(
  document: PDFKit.PDFDocument,
  beforeEnd?: () => void,
): Promise<Buffer> {
  const chunks: Buffer[] = [];
  document.on('data', (chunk: Buffer) => chunks.push(chunk));
  const complete = new Promise<Buffer>((resolve, reject) => {
    document.once('end', () => resolve(Buffer.concat(chunks)));
    document.once('error', reject);
  });
  beforeEnd?.();
  document.end();
  return complete;
}
